name: Progress Not Perfection
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74648
title: Progress Not Perfection
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6fbfe'
    - '#c9bcb6'
    - '#030000'
    - '#3d3a34'
    - '#a85419'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
