name: Progress Not Perfection
favicon: null
layout_spectrum: 0.8897173125296831
typography_spectrum: 0.8352759971749038
title: Progress Not Perfection
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6fbfe'
    - '#c9bcb6'
    - '#030000'
    - '#3d3a34'
    - '#a85419'
  brandStrength: 0.25
  lightness: 0.6848869358655065
  saturation: 0.7481349280569702
  rhythmicContrast: 0.6456207800656557
purpose: []
